export const ADD_COMMENT = 'ADD_COMMENT';
export const ONE_PRODUCT_LOADING = 'ONE_PRODUCTS_LOADING';
export const ONE_PRODUCT_FAILED = 'ONE_PRODUCTS_FAILED';
export const ADD_ONE_PRODUCT = 'ADD_ONE_PRODUCTS';
export const ADD_RESOURCES = 'ADD_RESOURCES';
export const RESOURCES_LOADING = 'RESOURCES_LOADING';
export const RESOURCES_FAILED = 'PRODUCTS_FAILED';

export const UPLOAD_PRODUCT_FAILED = 'UPLOAD_PRODUCT_FAILED';

export const UPLOAD_RESOURCE_FAILED = 'UPLOAD_RESOURCE_FAILED';
export const ONE_RESOURCE_LOADING = 'ONE_RESOURCES_LOADING';
export const ONE_RESOURCE_FAILED = 'ONE_RESOURCES_FAILED';
export const ADD_ONE_RESOURCE = 'ADD_ONE_RESOURCES';

export const ADD_DAILY_REPORTS = 'ADD_DAILY_REPORTS';
export const DAILY_REPORTS_LOADING = 'DAILY_REPORTS_LOADING';
export const DAILY_REPORTS_FAILED = 'DAILY_REPORTS_FAILED';

export const SET_USER = 'SET_USER';
export const SET_USER_FAILED = 'SET_USER_FAILED';
export const SET_USER_LOADING = 'SET_USER_LOADING';


export const ADD_STOCK = 'ADD_STOCK';
export const ADD_STOCK_LOADING = 'ADD_STOCK_LOADING';
export const ADD_STOCK_FAILED = 'ADD_STOCK_FAILED';

export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_LOADING = 'SIGN_UP_LOADING';
export const SIGN_UP_FAILED = 'SIGN_UP_FAILED';

export const ADD_INVOICE_DETAILS = 'ADD_INVOICE_DETAILS';
export const INVOICE_DETAILS_LOADING = 'INVOICE_DETAILS_LOADING';
export const INVOICE_DETAILS_FAILED = 'INVOICE_DETAILS_FAILED';

export const ADD_INVOICE = 'ADD_INVOICE_DETAILS';
export const INVOICE_LOADING = 'INVOICE_LOADING';
export const INVOICE_FAILED = 'INVOICE_FAILED';

export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';
export const RECOMMANDED_LOADING = 'RECOMMANDED_LOADING';
export const RECOMMANDED_FAILED = 'RECOMMANDED_FAILED';
export const ADD_RECOMMANDED = 'ADD_PROMOS';
export const HOTDEALS_LOADING = 'LEADERS_LOADING';
export const HOTDEALS_FAILED = 'LEADERS_FAILED';
export const ADD_HOTDEALS = 'ADD_LEADERS';
export const ADD_FEEDBACK = 'ADD_FEEDBACK';
export const FEEDBACK_FAILED = "FEEDBACK_FAILED";
export const FEEDBACK_LOADING = "FEEDBACK_LOADING";
export const OUT_OF_STOCK_PRODUCTS_LOADING = 'OUT_OF_STOCK_PRODUCTS_LOADING';
export const ADD_OUT_OF_STOCK_PRODUCTS = 'ADD_OUT_OF_STOCK_PRODUCTS';
export const OUT_OUT_STOCK_PRODUCTS_FAILED = 'OUT_OUT_STOCK_PRODUCTS_FAILED';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_TO_CART = 'REMOVE_TO_CART';
export const ADD_OR_REMOVE_TO_CART_LOADING = 'ADD_OR_REMOVE_TO_CART_LOADING';
export const CART_FAIL = 'CART_FAIL';


export const DISHES_LOADING = 'DISHES_LOADING';
export const DISHES_FAILED = 'DISHES_FAILED';
export const ADD_DISHES = 'ADD_DISHES';
export const PROMOS_LOADING = 'PROMOS_LOADING';
export const ADD_PROMOS = 'ADD_PROMOS';
export const PROMOS_FAILED = 'PROMOS_FAILED';
export const LEADERS_LOADING = 'LEADERS_LOADING';
export const ADD_LEADERS = 'ADD_LEADERS';
export const LEADERS_FAILED = 'LEADERS_FAILED';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const FAVORITES_LOADING = 'FAVORITES_LOADING';
export const FAVORITES_FAILED = 'FAVORITES_FAILED';
export const ADD_FAVORITES = 'ADD_FAVORITES';

export const FLIPPING_CARD_SAVE_ENABLE = 'FLIPPING_CARD_SAVE_ENABLE';
export const FLIPPING_CARD_SAVE_LOADING = 'FLIPPING_CARD_SAVE_LOADING';
export const FLIPPING_CARD_SAVE_DISABLE = 'FLIPPING_CARD_SAVE_DISABLE';

export const ADD_WAITERS = 'ADD_WAITERS';
export const WAITERS_LOADING = 'WAITERS_LOADING';
export const WAITERS_FAILURE = 'WAITERS_FAILURE';

export const PUSH_INVOICE = 'PUSH_INVOICE';
export const PUSH_INVOICE_LOADING = 'PUSH_INVOICE_LOADING';
export const PUSH_INVOICE_FAILURE = 'PUSH_INVOICE_FAILURE';

export const MISCELLANEOUS_LOADING = "MISCELLANEOUS_LOADING";
export const MISCELLANEOUS_FAILED = "MISCELLANEOUS_FAILED";
export const ADD_MISCELLANEOUS = "ADD_MISCELLANEOUS";
export const ADD_ONE_MISCELLANEOUS = "ADD_ONE_MISCELLANEOUS";

export const ADD_DAILY_INVOICE = "ADD_DAILY_INVOICE";
export const DAILY_INVOICE_FAILED = "DAILY_INVOICE_FAILED";
export const DAILY_INVOICE_LOADING = "DAILY_INVOICE_LOADING";
export const CHANGE_DAILY_INVOICE = "CHANGE_DAILY_INVOICE";


export const ADD_DAILY_INVOICE_DETAILS = "ADD_DAILY_INVOICE_DETAILS";
export const DAILY_INVOICE_DETAILS_FAILED = "DAILY_INVOICE_DETAILS_FAILED";
export const DAILY_INVOICE_DETAILS_LOADING = "DAILY_INVOICE_DETAILS_LOADING";
export const CHANGE_DAILY_DETAILS_INVOICE = "CHANGE_DAILY_INVOICE_DETAILS";
export const SET_PRODUCTS_IN_DAILY_INVOICE_DETAILS = "SET_PRODUCTS_IN_DAILY_INVOICE_DETAILS";

export const ADD_DAILY_STOCK_UP = "ADD_DAILY_STOCK_UP";
export const DAILY_STOCK_UP_FAILED = "DAILY_STOCK_UP_FAILED";
export const DAILY_STOCK_UP_LOADING = "DAILY_STOCK_UP_LOADING";
export const CHANGE_DAILY_STOCK_UP = "CHANGE_DAILY_STOCK_UP";
export const SET_PRODUCTS_IN_DAILY_STOCK_UP = "SET_PRODUCTS_IN_DAILY_STOCK_UP";